$script = <<SCRIPT
  sudo apt update
  sudo apt install -y python3 python3-pip libpq-dev
  pip3 install -q psycopg2-binary Django
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1804"
  config.vm.provision "shell", inline: $script
  config.vm.provision "file", source: "./foo.file", destination: "/tmp/foo.file"
  config.vm.provision "shell", inline: "sudo mv /tmp/foo.file /opt/foo.file"
end
